server {
    listen 80;
    server_name api.corbits.dev api.corbits.io;

    location /.well-known/acme-challenge/ {
        root /var/www/html;
    }

    location / {
        return 301 https://$host$request_uri;
    }
}

server {
    listen 443 ssl;
    server_name api.corbits.dev api.corbits.io;

    client_max_body_size 10m;

    include /etc/nginx/snippets/ssl-api.conf;
    include /etc/nginx/sites-available/control-plane.d/*.conf;
}
