user root;
worker_processes auto;
pid /usr/local/openresty/nginx/logs/nginx.pid;

events {
    worker_connections 1024;
}

http {
    server_names_hash_bucket_size 128;

    lua_package_path "/etc/nginx/?.lua;/etc/faremeter-gateway/?.lua;/etc/faremeter-gateway/*/?.lua;/usr/local/openresty/site/lualib/?.lua;/usr/local/openresty/lualib/?.lua;;";
    lua_shared_dict tenants 10m;
    lua_shared_dict word_dict 10m;
    lua_shared_dict fm_capture_buffer 10m;
    lua_ssl_trusted_certificate /etc/ssl/certs/ca-certificates.crt;
    lua_ssl_verify_depth 2;

    init_by_lua_file /etc/nginx/init-config.lua;

    include /etc/nginx/conf.d/*.conf;
}
